### ISSUE TITLE
service_id is undefined initially

### ISSUE THREAD

**Issue by JonathanSpeek** [fastly/compute-js-static-publish#1]
The first time I ran `fastly compute publish` on a fresh Gatsby site, I got what you see in the screenshot. See below (it was easy enough to just remove the string, but would be nice to fix). 

Change [this line](https://github.com/fastly/compute-js-static-publish/blob/3113b1400136a1d7a97519f4640a325081138768/src/init-app.ts#L26) to default to `''` rather than `undefined`

![CleanShot 2022-09-30 at 11 27 51@2x](https://user-images.githubusercontent.com/11696256/193325185-a3e59bbe-a905-4e39-b51a-346c7a36cff6.png)

**Comment by harmony7** [comment]
That's a really good point, I'll fix this.
