### ISSUE TITLE
Support HTTP compression

### ISSUE THREAD

**Issue by acme** [fastly/compute-js-static-publish#4]
To speed up published sites, we should serve compressed (Brotli & gzip) response bodies.

**Comment by harmony7** [comment]
gzip & deflate will be added in v4.

Brotli will need to come after https://github.com/fastly/js-compute-runtime/issues/114, but will be implemented soon after.

**Comment by harmony7** [comment]
Actually Brotli won't wait for that. For both gzip and br, we're going to support it at build time so that the package can contain the pre-compressed resources.

**Comment by harmony7** [comment]
This will be included in #6
